In [8]:
import pandas as pd

In [11]:
df= pd.read_excel(r"C:\Dropbox (Trilations)\3L - 0681 - Janssen LATAM Loyalty M1 2021\13. Modeling\4. MAF models\Model Combinations LATAM 2021M1 - MAF -Samira.xlsx", sheet_name='models')

In [12]:
df.head()

,model_nr,line_nr,country_region_name,d1ccode,country_region_code,ta_name,d1treatmentarea,own_company_name,own_company_code,own_brand_name,...,only_in_wave,equal_weight_over,weight_manual,weight_var,filter_var,models_to_run,zscore_over_split_on,extra_variables_for_datafile,Other remarks,Priority?
0,1,1,LATAM,"rgARG, rgBRA, rgCEN, rgCHL, rgCOL, rgMEX, rgPER",rgCLAT,MM,ta1,Janssen,co10,Darzalex,...,1,NaN,1.3333,ftwvar,ftkol,"maf_model,maf_model_comp","measurement, d1treatmentarea","ftresponseid, ftrespidunique, measurement",MAF Model,1
1,1,2,LATAM,"rgARG, rgBRA, rgCEN, rgCHL, rgCOL, rgMEX, rgPER",rgCLAT,MM,ta1,Janssen,co10,Darzalex,...,2,NaN,0.6666,ftwvar,ftkol,"maf_model,maf_model_comp","measurement, d1treatmentarea","ftresponseid, ftrespidunique, measurement",MAF Model,1
2,2,1,LATAM,"rgARG, rgBRA, rgCEN, rgCHL, rgCOL, rgMEX, rgPER",rgCLAT,CLL,ta9,Janssen,co10,Imbruvica,...,1,NaN,1.3333,ftwvar,ftkol,"maf_model,maf_model_comp","measurement, d1treatmentarea","ftresponseid, ftrespidunique, measurement",MAF Model,1
3,2,2,LATAM,"rgARG, rgBRA, rgCEN, rgCHL, rgCOL, rgMEX, rgPER",rgCLAT,CLL,ta9,Janssen,co10,Imbruvica,...,2,NaN,0.6666,ftwvar,ftkol,"maf_model,maf_model_comp","measurement, d1treatmentarea","ftresponseid, ftrespidunique, measurement",MAF Model,1
4,3,1,LATAM,"rgARG, rgBRA, rgCEN, rgCHL, rgCOL, rgPER",rgCLAT,mCSPC,ta6,Janssen,co10,Erleada,...,1,NaN,1.3333,ftwvar,ftkol,"maf_model,maf_model_comp","measurement, d1treatmentarea","ftresponseid, ftrespidunique, measurement",MAF Model,1